# ─────────────────────────────────────────────────────────────────────────────
# Stage 1 — Install dependencies
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS deps

# Install libc compatibility layer needed by some native addons on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy package files first for better layer caching
COPY package.json package-lock.json* ./

RUN npm ci --omit=dev


# ─────────────────────────────────────────────────────────────────────────────
# Stage 2 — Build the Next.js application
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

# Copy installed node_modules from the deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the full source tree
COPY . .

# Build produces .next/standalone — a minimal self-contained server
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build


# ─────────────────────────────────────────────────────────────────────────────
# Stage 3 — Lean production image
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Bind to all interfaces inside the container
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Copy the standalone server bundle
COPY --from=builder /app/.next/standalone ./

# Copy static assets (CSS, JS chunks, images)
COPY --from=builder /app/.next/static ./.next/static

# Copy the public folder (favicons, etc.)
COPY --from=builder /app/public ./public

# Copy the monitor config — users can bind-mount their own version
COPY --from=builder /app/pingflow.config.json ./pingflow.config.json

# Set correct ownership
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

# server.js is the standalone entry point generated by Next.js
CMD ["node", "server.js"]

